pipeline {
	agent any
		stages {
			stage('Build') {
				steps {
					cd JenkinsExample/test/jenkins 
					javac GreetingImplTest.java
					java GreetingImplTest
					echo "Testing done"
				}
			}
		}
}
